sudo: false
language: node_js

git:
  depth: 3

branches:
  only:
    - master
    - dev

node_js:
  - stable

before_script:
  # install dependencies
  - npm install -g gulp
  - npm install -g typescript
  # compile typescript
  - tsc -p ./

script:
  # execute all tests & gen code coverage report
  - "./node_modules/karma/bin/karma start ./config/karma.js --single-run"
  # vet all code
  - "gulp vet-lib-ts --verbose"

after_script:
  # send code coverage report to coveralls.io
  - "cat ./coverage/**/lcov.info | ./node_modules/coveralls/bin/coveralls.js"

notifications:
  slack:
    secure: SdyPKvuTLB9AmBC8g8nt6w6Qc3XDoQ6ICpSyfM1TDNNC+KvIsxw0ahpx9AvpBDbXTZNdyzcmAtHjUOAXbrCbTA0/6+rDEDHYTat4ZNiRhSJoJPjpV3hzeCVxT47jnljGrmzEUV/AhlcMJOIrn2Z5v2MoFmGHqyuhpOJqsz1KgppPMGRrmUrH779EZng/n6+JFQbDmLlA87n7BjRgw7QyzkbQHBTdhrQbGmMa0TaKYkTmaigp1E5Zf15UTWxt5lB2bH/v18fnF3cU9FHArr4PKi90ypx8FkNEthaSBCHFTVbrN3DXjCNAhyrBiomkJC2ML1gbBC/fskMDgektWfuSXftQt8zGOeMOT/+cAtNCQ7cTQ2lZ4lizKd5/+t0CSXeiUIsVcKEkgiYXdBHwSTf7Qfj2Zrjwl23tSFIag/IBgjZm++5LmfhSkQN95A9xxXUQzlcfUK2snflwH3FnygEqvbTbmSuMGzp4piHIcwCcNkcmYl8vfrA31ks8mHg648k5LFemO+7kPlAoEccBLkWJ4UVqpKN786jz4qHXTljj50pHWJXfuigh2ueuKAWnerBi/jodA/8nmyLuKOetogDJs7i0484SQ/x2jRqj7zOTCXbh3TB0msOQZlfJ38oymrl8eLI2IrLSefD3+Pct/z1Emmz6WFALQpWKXROdt7EvGao=
